### ISSUE TITLE
Ratio pattern not found in Steam version of The Final Season

### ISSUE THREAD

**Issue by RoseTheFlower** [PhantomGamers/TellTaleWidescreenPatcher#1]
The path is set to WalkingDead4.exe, the resolution selected is 2560x1080. Clicking on Patch results in ratio pattern not being found.

**Comment by PhantomGamers** [comment]
Fixed in version 1.1!

**Comment by RoseTheFlower** [comment]
Thank you. It goes through and removes the black bars as intended now.
