### ISSUE TITLE
Sam And Max Season 3 Not working

### ISSUE THREAD

**Issue by RandomGreenKirb** [PhantomGamers/TellTaleWidescreenPatcher#11]
Everytime i try to use the patcher it keeps displaying an error (FIX PATTERN NOT FOUND. EXECUTABLE IS NOT SUPPORTED)

**Comment by PhantomGamers** [comment]
This is fixed in 1.5 of the patcher ~~but sadly #10 still needs to be resolved~~

**Comment by RandomGreenKirb** [comment]
im using the 1.5 version of the patcher
