### ISSUE TITLE
New tales from the borderlands

### ISSUE THREAD

**Issue by Deventer4ever** [PhantomGamers/TellTaleWidescreenPatcher#13]
Hi Chris, how are you?
Could you kindly adapt the Telltale Fixer to New Tales from the borderlands? 
The solution fws/wolf among us does not work.
![FWS wolf among us](https://user-images.githubusercontent.com/105868570/204148533-203fb547-7934-4279-b821-11a9c03c07e5.jpg)
![New Tales From The Borderlands Screenshot 2022 11 27 - 17 38 34 63](https://user-images.githubusercontent.com/105868570/204148550-34da6ecd-db70-4564-9add-2ceacec15f05.png)

Many greetings in advance to the big apple from Germany!

Sascha

**Comment by PhantomGamers** [comment]
This game is not made by Telltale and uses Unreal Engine and not the Telltale game engine so it's kinda out of the scope of this patcher. This patcher is mainly intended for games using the Telltale game engine, and actually even Telltale is switching to Unreal engine so I don't think this tool will be updated for those games either, but there will likely be solutions either on Flawless Widescreen or solutions that use https://github.com/PhantomGamers/SUWSF for those games.

I can't do anything about this game for that either because I don't currently own it, though I may pick it up while it's on sale and see if I can't figure anything out.

**Comment by Deventer4ever** [comment]
Hi Chris, what a fast response. Thank you for your explanations (UE). Don´t know that so far... Can't you change something with a hex editor? But I don't know what to look for. I'm not a programmer.
![image](https://user-images.githubusercontent.com/105868570/204149528-880b8062-480a-42a1-b85c-473cf1bbaf6d.png)
In the meantime I´ll try your universal fixer. It sound´s wonderfull. If it works I tell (tale) you... LOL!!!

**Comment by Deventer4ever** [comment]
Hello, nothing happened.... O(
![image](https://user-images.githubusercontent.com/105868570/204151239-1440f083-19e8-464d-80ac-0e7ca568dc1e.png)

**Comment by PhantomGamers** [comment]
you need to put it in like Cypress2Game/Binaries or something, there will be another exe in there somewhere. but probably the default configuration of suwsf won't work anyway. can't hurt to try though

**Comment by Deventer4ever** [comment]
Tried it. Game woun´t start...
![image](https://user-images.githubusercontent.com/105868570/204152026-27eabeb1-e680-4dbd-bb60-21eff34ae0d7.png)

**Comment by Deventer4ever** [comment]
Hi Chris, tried to fix it with hex. I changed 2 values but no effect.
![image](https://user-images.githubusercontent.com/105868570/204160928-9c03d400-93cb-41ca-bd0d-50ee36437566.png)

**Comment by Deventer4ever** [comment]
Game do not start with SUWSF 2.3.0
![image](https://user-images.githubusercontent.com/105868570/204161179-b6f122ad-a458-4f1c-902d-30e62eb074f8.png)
Found the folder Win64 and extract the files.
![image](https://user-images.githubusercontent.com/105868570/204161223-654a4301-96b3-44e1-b198-85d030e8e1aa.png)

**Comment by PhantomGamers** [comment]
You should probably open an issue over on SUWSF for that, make sure to follow the instructions in that readme to try different names for the dsound.dll

**Comment by Deventer4ever** [comment]
Made it! Now SUWSF runs, but no screenfix. 
![image](https://user-images.githubusercontent.com/105868570/204163659-b76c8206-ad7f-492f-942e-5f11f18c04b6.png)
![New Tales From The Borderlands Screenshot 2022 11 27 - 23 41 52 14](https://user-images.githubusercontent.com/105868570/204163671-b54b2bdb-c6f1-4cf6-99c5-60ddddcb2d5d.png)

**Comment by Deventer4ever** [comment]
Found a solution without SUWSF!
![image](https://user-images.githubusercontent.com/105868570/204164293-6b596715-4a0a-40f1-b770-0b9401c4f75f.png)
![image](https://user-images.githubusercontent.com/105868570/204164244-8e989fa3-9a35-4c59-a121-126d45a99d74.png)
Thank´s for your hints!
