### ISSUE TITLE
16:10 resolutions?

### ISSUE THREAD

**Issue by supersonic124** [PhantomGamers/TellTaleWidescreenPatcher#15]
Any chance an option for 1280x800 or 16:10 resolutions could be added? On the Steam Deck Telltale's games always display at 16:9 with black bars on the top and bottom and there's nothing really close besides this program that can really modify resolutions for tt's games

**Comment by zqpvr** [comment]
@PhantomGamers I also need this

**Comment by PhantomGamers** [comment]
I added 16:10 support in a new release https://github.com/PhantomGamers/TellTaleWidescreenPatcher/releases/tag/1.7.0

I marked it as a prerelease because I did a lot of work on the code and didn't have a chance to thoroughly test it, but it seems to be working fine.

**Comment by zqpvr** [comment]
> I added 16:10 support in a new release https://github.com/PhantomGamers/TellTaleWidescreenPatcher/releases/tag/1.7.0
> 
> I marked it as a prerelease because I did a lot of work on the code and didn't have a chance to thoroughly test it, but it seems to be working fine.

works great on steam deck.

**Comment by supersonic124** [comment]
Awesome news, thanks for all your work
