### ISSUE TITLE
Walking Dead Season 2 Episode 1 Blackscreen with mouse cursor

### ISSUE THREAD

**Issue by Githuber5621** [PhantomGamers/TellTaleWidescreenPatcher#23]
After finished Season 1, I can finally play Season 2 but when i was at the part where clem is going inside of the house to steal some stuff for patching her arm and then that Blackscreen with mouse cursor happened. I cant do anything unless I alt+f4 and verify the game's files to fix that issue

Edit: im apologize its not this mod that cause the issue, its the relight mod. You can remove this issue.

**Comment by PhantomGamers** [comment]
Are you running the latest version of that mod? According to https://www.nexusmods.com/thewalkingdeadthetelltaledefinitiveseries/mods/1?tab=bugs it's supposed to be fixed in version 0.2
