### ISSUE TITLE
The Walking Dead - The Final Season 'ERROR COULD NOT PATCH STEAM FILE'

### ISSUE THREAD

**Issue by Soulketcher** [PhantomGamers/TellTaleWidescreenPatcher#3]
Hi and thank you for your work, I enjoyed your patcher on TWD - The New Frontier, worked flawlessly. But, went to use it on TWD - The Final Season, and it just says 'ERROR COULD NOT PATCH STEAM FILE' as I said in title, it is indeed the Steam version - Please see the attached JPG which shows you the version and date numbers. Thank you for your response, I appreciate it!

![THEWALKINGDEAD4 EXE - DETAILS TAB](https://user-images.githubusercontent.com/50709553/57864332-b2003280-77c9-11e9-9c26-8073c3e376e4.JPG)

**Comment by Soulketcher** [comment]
I figured I should attach the ACTUAL exe, in ZIP form, maybe you can get a better idea by working with it directly. I appreciate it, thank you! 
[WalkingDead4.zip](https://github.com/PhantomGamers/TellTaleWidescreenPatcher/files/3187702/WalkingDead4.zip)

**Comment by PhantomGamers** [comment]
Thanks for including the exe, I'm not home currently but I'll look into it as soon as I get home and keep you posted.

**Comment by PhantomGamers** [comment]
Are you using the cracked version of the game, or do you own it on Steam?

I don't own the game on Steam myself, but someone who does checked your exe and it doesn't match what's downloaded by Steam. If you own the game on Steam, try verifying your game cache integrity and/or reinstalling the game. The patcher definitely still works with the Steam version.

**Comment by Soulketcher** [comment]
Yeah, thank you, I had a feeling that might be the issue, it is a cracked version :( I guess I'm S.O.L? I do appreciate your quick response and your work, Thanks again to you and whoever took a peak at the exe.

**Comment by PhantomGamers** [comment]
I'm not planning on going out of my way to support cracked versions, if someone else wanted to look into what needs to be changed in the cracked version and submit a pull request with the additional signatures needed I'd accept it, but that's all I can offer.
